services:
  holy-church:
    container_name: holy-church
    build:
      context: .
      dockerfile: Dockerfile
    image: holy-church
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: holy-church-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: holychurch
      POSTGRES_PASSWORD: holychurch
      POSTGRES_DB: holy_church
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
