services:
  wealth-bridge-web:
    hostname: wealth-bridge-web
    container_name: wealth-bridge-web
    depends_on:
      - wealth-bridge-api
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./apps/web/.env.prod
    networks:
      - wealth-bridge_app_network

  wealth-bridge-api:
    hostname: wealth-bridge-api
    container_name: wealth-bridge-api
    depends_on:
      - wealth-bridge_db
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8000
    env_file:
      - ./apps/api/.env.prod
    networks:
      - wealth-bridge_app_network

  wealth-bridge-db:
    image: postgres:17-alpine3.21
    hostname: wealth-bridge-db
    container_name: wealth-bridge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wealth_bridge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    networks:
      - wealth-bridge_app_network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U postgres -d postgres',
        ]
      interval: 5s
      timeout: 2s
      retries: 20

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  wealth-bridge_app_network:
